### PR TITLE
BugFix for Linux screenshots

### PR DESCRIPTION
**Pull request by Robadob**
Initial work on BugFix for Linux screenshots not including occluded parts of the backbuffer.

Plan is to render the scene to a texture, which is then blit to the framebuffer.

This currently works, however multisampling is disabled, extra work is required to get that back.

### CODE REVIEW

**Comment by Robadob** [comment]
This should be working, with MSAA support now @ptheywood.

If you can confirm it works, then I'll squash the branch.

Then we just need to decide if we're happy with the solution (I don't think the impact of this blitting is supposed to be too significant on modern hardware, and I can't tell a difference to perf locally).

**Comment by ptheywood** [comment]
Yep still working for me when screenshotting with a portion of the window outside my X display region.

**Comment by Robadob** [comment]
Will amend this PR slightly before merge. Want to prevent framebuffer from using GL API stuff on resize() if resize is unnecessary.

**Comment by Robadob** [comment]
Have fixed that, fixed the screenshot buffer not being deallocated, and squashed. Will merge after CI is happy.

**Review by ptheywood — APPROVED** [review]

**Pull request merged**
