### PR TITLE
Fix some linting issues + add CI linting

### PR DESCRIPTION
**Pull request by ptheywood**
Big changes to Cmake to allow lint configurations without GL or CUDA. 

If cmake is configured and CUDA or openGL are unavailable, but CPPLint is available,  a status message is produced stating that this is a lint only build. 

This also only lints teh contents of this repo. The visualisation only components of the main repo still avoid lint CI at present. It will be *much* more difficult to make that repo lint only... 

```
cmake .. 
-- Lint-only build configuraiton due to missing dependencies
-- CUDA is required for building
-- Configuring done
-- Generating done
```

Potentially it might be better to make lint only builds opt in? I.e. error if CUDA or OpenlGL not found, unless `-DLINT_ONLY=ON` or similar?

Testing: 
+ [x] Local Linux working with and without CUDA
+ [x] Local linux when included from FLAMEGPU2
+ [x] Linux CI without CUDA (or GL) 
+ [ ] Windows

### CODE REVIEW

**Comment by Robadob** [comment]
> Potentially it might be better to make lint only builds opt in? I.e. error if CUDA or OpenlGL not found, unless -DLINT_ONLY=ON or similar?

Yes

And yeah I want to test this fixes the issue with lint wanting includes to begin `src/`, will get to it tonight. Still fiddling primage atm.

**Comment by ptheywood** [comment]
> > Potentially it might be better to make lint only builds opt in? I.e. error if CUDA or OpenlGL not found, unless -DLINT_ONLY=ON or similar?
> 
> Yes
> 
> And yeah I want to test this fixes the issue with lint wanting includes to begin `src/`, will get to it tonight. Still fiddling primage atm.

I've not intentionally addressed that, but linting passes under linux from this repo and the core repo for me. I'll add the cmake option.

**Comment by ptheywood** [comment]
```
cmake ..
CMake Error at CMakeLists.txt:326 (message):
  CUDA is required for building


-- Configuring incomplete, errors occurred!
```

```
cmake .. -DALLOW_LINT_ONLY=ON
-- Lint-only build configuraiton due to missing dependencies
-- CUDA is required for building
-- Configuring done
-- Generating done
-- Build files have been written to: 
```

**Comment by Robadob** [comment]
We could make the CI action build visualiser, no reason it can't.
Visualiser builds standalone, it's just a bit useless.

**Comment by ptheywood** [comment]
OpenGL + CUDA are dependencies. Just the dev packages should be doable though. 

This PR does appear to have fixed linitng the visualiser from an example for me. I'll try the same fix for the main repo. (the `--root` code was already in the vis repo).

**Comment by Robadob** [comment]
Running the `lint_flamegpu2_visualiser` target, via visual studio (this existed prior to your changes, I think the issue is they use the rule about root which matches fgpu2 main lib files. I don't think we've ever tested the same lint rule for examples, so they could be affected too), still gives these errors. I don't see a new/different lint target either.

```
1>C:/Users/Robadob/fgpu2_vis/src/Visualiser.cpp(2): error cpplint: [build/include] src/Visualiser.cpp should include its header file src/Visualiser.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/util/Resources.cpp(13): error cpplint: [build/include] src/util/Resources.cpp should include its header file src/util/Resources.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Axis.cpp(None) : error cpplint: [build/include] src/Axis.cpp should include its header file src/Axis.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Draw.cpp(3): error cpplint: [build/include] src/Draw.cpp should include its header file src/Draw.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Entity.cpp(3): error cpplint: [build/include] src/Entity.cpp should include its header file src/Entity.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/HUD.cpp(3): error cpplint: [build/include] src/HUD.cpp should include its header file src/HUD.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Overlay.cpp(3): error cpplint: [build/include] src/Overlay.cpp should include its header file src/Overlay.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Sprite2D.cpp(2): error cpplint: [build/include] src/Sprite2D.cpp should include its header file src/Sprite2D.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Text.cpp(3): error cpplint: [build/include] src/Text.cpp should include its header file src/Text.h [5]
```

**Comment by Robadob** [comment]
Of those errors, `Resources.cpp` is a legit error.

The issue appears to only affect headers which exist in the root.

**Comment by Robadob** [comment]
Woops I forgot to test this.

**Comment by Robadob** [comment]
Done your rebase, basically manually readded the `CMakeLists.txt` changes to your file, bc the conflict was nasty.

Still getting these errors for root project when cmaking via visual studio big project. All files in root directory, told they need to include with `src/`. Will have a brief look into whether I can fix that now.

```
1>C:/Users/Robadob/fgpu2_vis/src/Visualiser.cpp(2): error cpplint: [build/include] src/Visualiser.cpp should include its header file src/Visualiser.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Axis.cpp(None) : error cpplint: [build/include] src/Axis.cpp should include its header file src/Axis.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Draw.cpp(3): error cpplint: [build/include] src/Draw.cpp should include its header file src/Draw.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Entity.cpp(3): error cpplint: [build/include] src/Entity.cpp should include its header file src/Entity.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/HUD.cpp(3): error cpplint: [build/include] src/HUD.cpp should include its header file src/HUD.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Overlay.cpp(3): error cpplint: [build/include] src/Overlay.cpp should include its header file src/Overlay.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Sprite2D.cpp(2): error cpplint: [build/include] src/Sprite2D.cpp should include its header file src/Sprite2D.h [5]
1>C:/Users/Robadob/fgpu2_vis/src/Text.cpp(3): error cpplint: [build/include] src/Text.cpp should include its header file src/Text.h [5]
```

**Comment by Robadob** [comment]
Ah, the issue appears to be that CMake is locating `C:\Python27\Scripts\cpplint.exe`, rather than my python3 version which I updated. I'll manually update that should fix.

**Comment by Robadob** [comment]
Well that failed, will just nuke the directory I guess.

image

**Comment by Robadob** [comment]
Yup, working for me now. Good job.

**Pull request merged**
